Ext.define('SFCT.store.EnglishWordsFirst', {
    extend: 'Ext.data.Store',
    config: {
        model: 'SFCT.model.Word',
        data: [

            {word: 'in',    english: ''},
            {word: 'will',    english: ''},
            {word: 'of',    english: ''},
            {word: 'this',    english: ''},
            {word: 'your',    english: ''},
            {word: 'one',    english: ''},
            {word: 'good',    english: ''},
            {word: 'me',    english: ''},
            {word: 'about',    english: ''},
            {word: 'if',    english: ''},
            {word: 'some',    english: ''},
            {word: 'so',    english: ''},
            {word: 'very',    english: ''},
            {word: 'would',    english: ''},
            {word: 'any',    english: ''},
            {word: 'been',    english: ''},
            {word: 'out',    english: ''},
            {word: 'day',    english: ''},
            {word: 'then',    english: ''},
            {word: 'us',    english: ''},
            {word: 'no',    english: ''},
            {word: 'him',    english: ''},
            {word: 'get',    english: ''},
            {word: 'two',    english: ''},
            {word: 'man',    english: ''},
            {word: 'little',    english: ''},
            {word: 'has',    english: ''},
            {word: 'them',    english: ''},
            {word: 'our',    english: ''},
            {word: 'know',    english: ''},
            {word: 'make',    english: ''},
            {word: 'which',    english: ''},
            {word: 'much',    english: ''},
            {word: 'who',    english: ''},
            {word: 'their ',    english: ''},
            {word: 'new',    english: ''},
            {word: 'did',    english: ''},
            {word: 'boy',    english: ''},
            {word: 'three',    english: ''},
            {word: 'down',    english: ''},
            {word: 'work',    english: ''},
            {word: 'put',    english: ''},
            {word: 'before',    english: ''},
            {word: 'just',    english: ''},
            {word: 'long',    english: ''},
            {word: 'other',    english: ''},
            {word: 'old',    english: ''},
            {word: 'take',    english: ''},
            {word: 'cat',    english: ''},
            {word: 'again',    english: ''},
            {word: 'give',    english: ''},
            {word: 'after',    english: ''},
            {word: 'many',    english: ''},
            {word: 'saw',    english: ''},
            {word: 'home',    english: ''},
            {word: 'soon',    english: ''},
            {word: 'stand',    english: ''},
            {word: 'box',    english: ''},
            {word: 'upon',    english: ''},
            {word: 'first',    english: ''},
            {word: 'came',    english: ''},
            {word: 'girl',    english: ''},
            {word: 'house',    english: ''},
            {word: 'find',    english: ''},
            {word: 'because',    english: ''},
            {word: 'made',    english: ''},
            {word: 'could',    english: ''},
            {word: 'book',    english: ''},
            {word: 'mother',    english: ''},
            {word: 'run',    english: ''},
            {word: 'school',    english: ''},
            {word: 'people',    english: ''},
            {word: 'night',    english: ''},
            {word: 'into',    english: ''},
            {word: 'say',    english: ''},
            {word: 'think',    english: ''},
            {word: 'back',    english: ''},
            {word: 'big',    english: ''},
            {word: 'where',    english: ''},
            {word: 'am',    english: ''},
            {word: 'ball',    english: ''},
            {word: 'morning',    english: ''},
            {word: 'live',    english: ''},
            {word: 'four',    english: ''},
            {word: 'last',    english: ''},
            {word: 'color',    english: ''},
            {word: 'away',    english: ''},
            {word: 'red',    english: ''},
            {word: 'friend',    english: ''},
            {word: 'pretty',    english: ''},
            {word: 'eat',    english: ''},
            {word: 'want',    english: ''},
            {word: 'year',    english: ''},
            {word: 'white',    english: ''},
            {word: 'got',    english: ''},
            {word: 'found',    english: ''},
            {word: 'left',    english: ''},
            {word: 'men',    english: ''},
            {word: 'bring',    english: ''},
            {word: 'wish',    english: ''}

        ]
    }
});
