Ext.define('SFCT.store.EnglishWordsK', {
    extend: 'Ext.data.Store',
    config: {
        model: 'SFCT.model.Word',
        data: [

            {word: 'see',    english: ''},
            {word: 'I',    english: ''},
            {word: 'a',    english: ''},
            {word: 'is ',    english: ''},
            {word: 'like',    english: ''},
            {word: 'my',    english: ''},
            {word: 'are',    english: ''},
            {word: 'with',    english: ''},
            {word: 'play',    english: ''},
            {word: 'have',    english: ''},
            {word: 'can',    english: ''},
            {word: 'was',    english: ''},
            {word: 'he',    english: ''},
            {word: 'she',    english: ''},
            {word: 'the',    english: ''},
            {word: 'you',    english: ''},
            {word: 'and',    english: ''},
            {word: 'here',    english: ''},
            {word: 'were',    english: ''},
            {word: 'his',    english: ''},
            {word: 'her',    english: ''},
            {word: 'said',    english: ''},
            {word: 'they',    english: ''},
            {word: 'we',    english: ''},
            {word: 'to',    english: ''},
            {word: 'go',    english: ''},
            {word: 'it',    english: ''},
            {word: 'up',    english: ''},
            {word: 'look',    english: ''},
            {word: 'do',    english: ''},
            {word: 'an',    english: ''},
            {word: 'love',    english: ''},
            {word: 'as',    english: ''},
            {word: 'at',    english: ''},
            {word: 'on',    english: ''},
            {word: 'not',    english: ''},
            {word: 'all',    english: ''},
            {word: 'there',    english: ''},
            {word: 'by',    english: ''},
            {word: 'but',    english: ''},
            {word: 'had',    english: ''},
            {word: 'how',    english: ''},
            {word: 'what',    english: ''},
            {word: 'come',    english: ''},
            {word: 'or',    english: ''},
            {word: 'that',    english: ''},
            {word: 'from',    english: ''}

        ]
    }
});
